# Generated by Django 5.0.6 on 2024-06-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='publ_date',
            new_name='pub_date',
        ),
    ]
